default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter-bot_development

test:
  <<: *default
  database: twitter-bot_test

production:
  <<: *default
  database: twitter-bot_production
  username: twitter-bot
  password: <%= ENV['TWITTER-BOT_DATABASE_PASSWORD'] %>
